//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStudioProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Администратор
    {
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public int КодАдминистратора { get; set; }
        public Nullable<int> IDuser { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
    }
}
