//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStudioProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Задание
    {
        public int КодИсполнителя { get; set; }
        public int КодРаботы { get; set; }
        public int КодЗаказа { get; set; }
        public Nullable<System.DateTime> ФактВремяНачала { get; set; }
        public Nullable<System.DateTime> ФактВремяЗавершения { get; set; }
        public Nullable<int> ПорядковыйНомер { get; set; }
        public Nullable<System.DateTime> КрайнийСрокВыполненияРаботы { get; set; }
        public int КодЗадания { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Исполнитель Исполнитель { get; set; }
        public virtual Работа Работа { get; set; }
    }
}
