//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStudioProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Задание = new HashSet<Задание>();
        }
    
        public Nullable<System.DateTime> ДатаЗаказа { get; set; }
        public Nullable<decimal> СтоимостьЗаказа { get; set; }
        public int КодЗаказа { get; set; }
        public int КодЗаказчика { get; set; }
        public Nullable<int> КодСтатуса { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Задание> Задание { get; set; }
        public virtual Заказчик Заказчик { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
