//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStudioProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Исполнитель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Исполнитель()
        {
            this.Задание = new HashSet<Задание>();
        }
    
        public int КодИсполнителя { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> IDuser { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public Nullable<decimal> Заработная_плата { get; set; }
        public int КодСпециальности { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Задание> Задание { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Специальности Специальности { get; set; }
    }
}
