//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStudioProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Работа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Работа()
        {
            this.Задание = new HashSet<Задание>();
        }
    
        public int КодРаботы { get; set; }
        public string Название { get; set; }
        public Nullable<decimal> СтоимостьРаботы { get; set; }
        public Nullable<int> Длительность { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Задание> Задание { get; set; }
    }
}
